GET http://localhost:3000/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJjbG9uZTAiLCJfaWQiOiI2MTY3ZDg3MzZjNzI0NDhhYjc0ZDVmZTkiLCJpYXQiOjE2MzQxOTg5NTYsImV4cCI6MTYzNDE5ODk1OX0.5WNKeruZzdrfE2A6i1eBM9t2jAB0pYC1WHyLq1Fxq2E
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "userclone0",
    "password": "userclone"
}
###

POST http://localhost:5000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY3ZjYxODYzMjNjMGQ0YWE1NTY2NGIiLCJ1c2VybmFtZSI6InVzZXJjbG9uZTAiLCJpYXQiOjE2MzQyMTAyMzAsImV4cCI6MTYzNDIxMzgzMH0.IfNqIA14fm4VZ7bVt3HjLD9Xy7VMftudPXvujmzqmuE"
}